#READ BEFORE RUNNING !!!

#These models might take a while to run and will save model outputs to the current directory
#For convenience, the model outputs are already saved to load and analyze so you don't have to run them from scratch
#All models generated by this script are saved in the regression-models folder
#Models are loaded and analyzed in the analyze-bayesian-RTregressions script

#this script is mainly provided for examination of data preprocessing and the code used to generate models
#it is not recommended you try to run this whole script for reasons noted above

#script assumes the same folder structure as the OSF analyses directory

library(brms)

####read in raw data files####
setwd("../rawdata/")
files = list.files(pattern = "*.txt")
for(file in files){
  thisdf<-read.table(file, header = T)
  if (file == files[1]){
    fulldf<-thisdf
  }
  else{
    fulldf<-rbind(thisdf, fulldf)
  }
}
setwd("../RTanalyses/")



####preproc/data cleaning####
voldf<-subset(fulldf, task_cue == "?")
expdf<-subset(fulldf, task_cue != "?")

#set switches correctly for voldf
library(data.table)
voldf$sr[voldf$task != shift(voldf$task)]<-1
voldf$sr[voldf$task == shift(voldf$task)]<-0
voldf$sr[voldf$altRep == -1]<- -1

#remove subjects with bad switch rats from voldf
srtots<-aggregate(sr ~ subj, data = subset(voldf, altRep > -1), FUN = mean)
badsubs<-srtots$subj[srtots$sr > .8 | srtots$sr < .2]

voldf<-subset(voldf, !(subj %in% badsubs))

#remove bad accuracies from both
acctots_exp<-aggregate(task_acc ~ subj, data = expdf, FUN = mean)
badsubs<-acctots_exp$subj[acctots_exp$acc < .6]
expdf<-subset(expdf, !(subj %in% badsubs))

acctots_vol<-aggregate(task_acc ~ subj, data = voldf, FUN = mean)
badsubs<-acctots_vol$subj[acctots_vol$acc < .6]
voldf<-subset(voldf, !(subj %in% badsubs))

voldf$altRep<-voldf$sr
voldf$subj<-as.factor(voldf$subj)
expdf$subj<-as.factor(expdf$subj)
voldf$altRep<-as.factor(voldf$altRep)
expdf$altRep<-as.factor(expdf$altRep)
voldf$CSI<-as.factor(voldf$CSI)
expdf$CSI<-as.factor(expdf$CSI)
voldf$RSI<-as.factor(voldf$RSI)
expdf$RSI<-as.factor(expdf$RSI)

#output files had response-cue interval incorrectly named as response-stimulus interval
colnames(voldf)[17]<-'RCI'
colnames(expdf)[17]<-'RCI'

#add column that has each interval combination as a condition
voldf$intervals<-paste(voldf$RCI, voldf$CSI, sep=".")

expdf$intervals<-paste(expdf$RCI, expdf$CSI, sep=".")

###
voldf<-subset(voldf, altRep != "-1")
expdf<-subset(expdf, altRep != "-1")

voldf<-subset(voldf, E1 < 1)
expdf<-subset(expdf, E1 < 1)

voldf<-subset(voldf, taskRT < (mean(taskRT) + 3*sd(taskRT)))
expdf<-subset(expdf, taskRT < (mean(taskRT) + 3*sd(taskRT)))

voldf<-subset(voldf, taskRT > 200)
expdf<-subset(expdf, taskRT > 200)

voldf$logRT<-log(voldf$taskRT)
expdf$logRT<-log(expdf$taskRT)

####effect of switching on log RT within each interval condition####
volSS<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(voldf, RCI=="100" & CSI=="100"))
saveRDS(volSS, 'voluntary-SwitchCost-SS-mod.rds')

volSL<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(voldf, RCI=="100" & CSI=="1000"))
saveRDS(volSL, 'voluntary-SwitchCost-SL-mod.rds')

volLS<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(voldf, RCI=="1000" & CSI=="100"))
saveRDS(volLS, 'voluntary-SwitchCost-LS-mod.rds')

volLL<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(voldf, RCI=="1000" & CSI=="1000"))
saveRDS(volLL, 'voluntary-SwitchCost-LL-mod.rds')

##

expSS<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(expdf, RCI=="100" & CSI=="100"))
saveRDS(expSS, 'explicit-SwitchCost-SS-mod.rds')

expSL<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(expdf, RCI=="100" & CSI=="1000"))
saveRDS(expSL, 'explicit-SwitchCost-SL-mod.rds')

expLS<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(expdf, RCI=="1000" & CSI=="100"))
saveRDS(expLS, 'explicit-SwitchCost-LS-mod.rds')

expLL<-brm(logRT ~ altRep+ (1 + altRep|subj), 
           data=subset(expdf, RCI=="1000" & CSI=="1000"))
saveRDS(expLL, 'explicit-SwitchCost-LL-mod.rds')

####comparison of log RT across interval pairs####
volSLLS_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(voldf, altRep == "1" & 
                              (intervals == "100.1000" | intervals=="1000.100") ))
saveRDS(volSLLS_sw, 'voluntary-switchRT-SL-LS-mod.rds')
volSLLS_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(voldf, altRep == "0" & 
                              (intervals == "100.1000" | intervals=="1000.100") ))
saveRDS(volSLLS_rep, 'voluntary-repRT-SL-LS-mod.rds')


volLSSS_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(voldf, altRep == "1" & 
                              (intervals == "1000.100" | intervals=="100.100") ))
saveRDS(volLSSS_sw, 'voluntary-switchRT-LS-SS-mod.rds')
volLSSS_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(voldf, altRep == "0" & 
                              (intervals == "1000.100" | intervals=="100.100") ))
saveRDS(volLSSS_rep, 'voluntary-repRT-LS-SS-mod.rds')

volLLSL_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(voldf, altRep == "1" & 
                              (intervals == "1000.1000" | intervals=="100.1000") ))
saveRDS(volLLSL_sw, 'voluntary-switchRT-LL-SL-mod.rds')
volLLSL_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                 data=subset(voldf, altRep == "0" & 
                               (intervals == "1000.1000" | intervals=="100.1000") ))
saveRDS(volLLSL_rep, 'voluntary-repRT-LL-SL-mod.rds')


volLLSS_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(voldf, altRep == "1" & 
                              (intervals == "1000.1000" | intervals=="100.100") ))
saveRDS(volLLSS_sw, 'voluntary-switchRT-LL-SS-mod.rds')
volLLSS_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                 data=subset(voldf, altRep == "0" & 
                               (intervals == "1000.1000" | intervals=="100.100") ))
saveRDS(volLLSS_rep, 'voluntary-repRT-LL-SS-mod.rds')

##

expSLLS_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(expdf, altRep == "1" & 
                              (intervals == "100.1000" | intervals=="1000.100") ))
saveRDS(expSLLS_sw, 'explicit-switchRT-SL-LS-mod.rds')
expSLLS_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                 data=subset(expdf, altRep == "0" & 
                               (intervals == "100.1000" | intervals=="1000.100") ))
saveRDS(expSLLS_rep, 'explicit-repRT-SL-LS-mod.rds')


expLSSS_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(expdf, altRep == "1" & 
                              (intervals == "1000.100" | intervals=="100.100") ))
saveRDS(expLSSS_sw, 'explicit-switchRT-LS-SS-mod.rds')
expLSSS_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                 data=subset(expdf, altRep == "0" & 
                               (intervals == "1000.100" | intervals=="100.100") ))
saveRDS(expLSSS_rep, 'explicit-repRT-LS-SS-mod.rds')

expLLSL_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(expdf, altRep == "1" & 
                              (intervals == "1000.1000" | intervals=="100.1000") ))
saveRDS(expLLSL_sw, 'explicit-switchRT-LL-SL-mod.rds')
expLLSL_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                 data=subset(expdf, altRep == "0" & 
                               (intervals == "1000.1000" | intervals=="100.1000") ))
saveRDS(expLLSL_rep, 'explicit-repRT-LL-SL-mod.rds')


expLLSS_sw<-brm(logRT ~ intervals + (1 + intervals|subj), 
                data=subset(expdf, altRep == "1" & 
                              (intervals == "1000.1000" | intervals=="100.100") ))
saveRDS(expLLSS_sw, 'explicit-switchRT-LL-SS-mod.rds')
expLLSS_rep<-brm(logRT ~ intervals + (1 + intervals|subj), 
                 data=subset(expdf, altRep == "0" & 
                               (intervals == "1000.1000" | intervals=="100.100") ))
saveRDS(expLLSS_rep, 'explicit-repRT-LL-SS-mod.rds')
